[package]
name = "gewe-skill-client"
version = "0.1.33"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
gewe-skill-types = { path = "../gewe-skill-types" }
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
url.workspace = true

[lints]
workspace = true
